name: Build and release
  
on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Build and release Suntan Kernel for gs101'
        required: true
        type: boolean
        default: false

jobs:
  build-kernel:
    uses: ./.github/workflows/build-kernel-gs101.yml
    secrets: inherit
